### ISSUE TITLE
Dependent extensions in TYPO3 v12 not available

### ISSUE THREAD

**Issue by brotkrueml** [sbuerk/typo3-cmscomposerinstallers-testingframework-bridge#7]
I have a custom extension which requires additional extensions. With TYPO3 v11 these dependent extensions are symlinked correctly in `.Build/Web/typo3conf/ext`. However, with TYPO3 v12 this fails, only the "root" extension is successfully symlinked.

I tracked it down to `PluginService::buildRootExtesionLegacyExtMirror()` which calls `$this->filesystem->emptyDirectory($legacyExtPath, true);`:

1. `buildLegacyExtMirror()` symlinks the dependent extensions correctly.
2. `buildRootExtesionLegacyExtMirror()` clears the extension folder with the symlinked extensions again.

After removing `$this->filesystem->emptyDirectory($legacyExtPath, true);` all extensions in the `typo3conf/ext/` folder are symlinked, like expected.

The behaviour can be tested with https://github.com/brotkrueml/typo3-jobrouter-data: The extensions `jobrouter_connector` and `jobrouter_base` are required in `composer.json` and not symlinked in TYPO3 v12.

**Comment by sbuerk** [comment]
Thanks for the reporting - will have a look later on this.
